const auth = {
  login: "تسجيل الدخول",
  register: "إنشاء حساب",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  forgotPassword: "نسيت كلمة المرور؟",
  signIn: "تسجيل دخول",
  signUp: "إنشاء حساب",
  createAccount: "إنشاء حساب جديد",
  noAccount: "ليس لديك حساب؟",
  haveAccount: "لديك حساب بالفعل؟",
  loginWelcome: "مرحباً! أهلاً بك من جديد",
  registerWelcome: "هيا بنا! سجل في ثوانٍ.",
  confirmPasswordPlaceholder: "أعد إدخال كلمة المرور الخاصة بك",
  forgotPasswordtitle: "نسيت كلمة المرور؟",
  forgotPasswordDesc: "أدخل بريدك الإلكتروني لتلقي رابط الاستعادة.",
  sendLink: "إرسال رابط الاستعادة",
  linkSent: "تم إرسال الرابط!",
  recoveryEmailSent: "لقد أرسلنا رابط استعادة كلمة المرور إلى:\n",
  verifyEmail: "التحقق من البريد",
  verifyDesc: "لقد أرسلنا رمز التحقق إلى بريدك الإلكتروني.",
  otpCode: "رمز التحقق",
  verify: "تحقق",
  resendCode: "إعادة إرسال الرمز",
  didNotReceive: "لم تستلم الرمز؟",
  resend: "إعادة إرسال",
  justAMoment: "فقط لحظة...",
  successVerified: "تم التحقق من بريدك الإلكتروني بنجاح.\nيمكنك الآن البدء.",
  letsGo: "هيا بنا",
  verifyEmailTitle: "تحقق من بريدك الإلكتروني",
  verificationLinkSent: "تم إرسال رابط التحقق إلى\n",
  changeEmail: "تغيير البريد الإلكتروني؟",
  verifiedButton: "تم التحقق",
  didNotReceiveEmail: "لم تستلم البريد الإلكتروني؟ ",
};

export default auth;
