const common = {
  appName: "SnackDream",
  loading: "جاري التحميل...",
  error: "حدث خطأ ما",
  retry: "إعادة المحاولة",
  cancel: "إلغاء",
  save: "حفظ",
  done: "تم",
  next: "التالي",
  back: "رجوع",
  getStarted: "ابدأ الآن",
  continue: "استمرار",
  skip: "تخطي",
  confirm: "تأكيد",
  delete: "حذف",
  imageResult: "نتيجة الصورة",
  videoResult: "نتيجة الفيديو",
  saved: "تم الحفظ!",
  savedToGallery: "تم حفظ الصورة/الفيديو في المعرض.",
  deleteCreation: "حذف الابتكار",
  deleteConfirmMessage:
    "هل أنت متأكد أنك تريد حذف هذا الابتكار؟ لا يمكن التراجع عن هذا الإجراء.",
  logout: "تسجيل الخروج",
  logoutConfirm: "هل تريد حقاً تسجيل الخروج؟",
  deleteAccount: "حذف الحساب",
  deleteAccountConfirm: "حذف الحساب نهائياً؟ سيتم فقدان كل شيء.",
  privacyPolicy: "سياسة الخصوصية",
  termsConditions: "الشروط والأحكام",
  rateApp: "تقييم التطبيق",
  feedback: "الملاحظات",
  contactUs: "اتصل بنا",
  profile: "الملف الشخصي",
  creations: "الابتكارات",
  community: "المجتمع",
  share: "مشاركة",
  copy: "نسخ",
  copied: "تم النسخ!",
  regenerate: "إعادة إنتاج",
  download: "تحميل",
  or: "أو",
};

export default common;
