const common = {
  appName: "SnackDream",
  loading: "جاري التحميل...",
  error: "حدث خطأ ما",
  retry: "إعادة المحاولة",
  cancel: "إلغاء",
  save: "حفظ",
  done: "تم",
  credits: "الرصيد",
  images: "صور",
  next: "التالي",
  back: "رجوع",
  getStarted: "ابدأ الآن",
  continue: "استمرار",
  skip: "تخطي",
  confirm: "تأكيد",
  delete: "حذف",
  imageResult: "نتيجة الصورة",
  videoResult: "نتيجة الفيديو",
  saved: "تم الحفظ!",
  savedToGallery: "تم حفظ الصورة/الفيديو في المعرض.",
  deleteCreation: "حذف الابتكار",
  deleteConfirmMessage:
    "هل أنت متأكد أنك تريد حذف هذا الابتكار؟ لا يمكن التراجع عن هذا الإجراء.",
  logout: "تسجيل الخروج",
  logoutConfirm: "هل تريد حقاً تسجيل الخروج؟",
  deleteAccount: "حذف الحساب",
  deleteAccountConfirm: "حذف الحساب نهائياً؟ سيتم فقدان كل شيء.",
  privacyPolicy: "سياسة الخصوصية",
  termsConditions: "الشروط والأحكام",
  rateApp: "تقييم التطبيق",
  feedback: "الملاحظات",
  contactUs: "اتصل بنا",
  home: "الرئيسية",
  profile: "الملف الشخصي",
  creations: "الابتكارات",
  community: "المجتمع",
  share: "مشاركة",
  copy: "نسخ",
  copied: "تم النسخ!",
  regenerate: "إعادة إنتاج",
  download: "تحميل",
  or: "أو",
  removeImage: "حذف الصورة",
  removeImageConfirm: "هل أنت متأكد من حذف هذه الصورة؟",
  remove: "حذف",
  optional: "اختياري",
  maxImagesReached: "تم الوصول للحد الأقصى",
  maxImagesDesc: "يمكنك تحميل ما يصل إلى {max} صور فقط",
  noImages: "لا توجد صور",
  noImagesDesc: "يرجى تحميل صورة واحدة على الأقل",
  noPrompt: "لا يوجد وصف",
  noPromptDesc: "يرجى إدخال وصف",
  aiGenerate: "إنتاج بالذكاء الاصطناعي",
  aiGenerateDesc: "جاري إنتاج الوصف بالذكاء الاصطناعي...",
  modelSelection: "اختيار النموذج",
  modelSelectionDesc: "اختر نموذج الذاء الاصطناعي",
  ok: "موافق",
  oops: "عفواً!",
  notExist: "هذه الصفحة غير موجودة.",
  goHome: "العودة للرئيسية",
  unknownEffect: "تأثير غير معروف",
  unknownModel: "نموذج غير معروف",
  all: "الكل",
  image: "صورة",
  video: "فيديو",
};

export default common;
