export default {
  title: "اتصل بنا",
  desc: "لديك سؤال أو تحتاج إلى مساعدة؟ نحن هنا من أجلك! تواصل معنا من خلال أي من الطرق أدناه أو أرسل لنا رسالة.",
  getInTouch: "ابق على تواصل",
  sendMessage: "أرسل رسالة",
  emailUs: "أرسل لنا بريداً إلكترونياً",
  name: "الاسم",
  email: "البريد الإلكتروني",
  subject: "الموضوع",
  message: "الرسالة",
  namePlaceholder: "اسمك",
  emailPlaceholder: "your@email.com",
  subjectPlaceholder: "عن ماذا يدور الموضوع؟",
  messagePlaceholder: "أخبرنا كيف يمكننا مساعدتك...",
  send: "إرسال الرسالة",
  requiredFields: "حقول مطلوبة",
  fillAllFields: "يرجى ملء جميع الحقول",
  invalidEmail: "بريد إلكتروني غير صالح",
  invalidEmailDesc: "يرجى إدخال عنوان بريد إلكتروني صحيح",
  messageSent: "تم إرسال الرسالة!",
  messageSentDesc: "شكراً لتواصلك معنا. سنرد عليك في غضون 24-48 ساعة.",
  ok: "موافق",
};
