export default {
  title: "الملاحظات",
  desc: "نحن نقدر ملاحظاتك! ساعدنا في تحسين SnackDream من خلال مشاركة أفكارك، الإبلاغ عن الأخطاء، أو اقتراح ميزات جديدة.",
  category: "الفئة",
  bug: "إبلاغ عن خطأ",
  feature: "طلب ميزة",
  improvement: "تحسين",
  other: "أخرى",
  yourFeedback: "ملاحظاتك",
  feedbackPlaceholder: "أخبرنا بما يدور في ذهنك...",
  emailOptional: "البريد الإلكتروني (اختياري)",
  emailPlaceholder: "your@email.com",
  submit: "إرسال الملاحظات",
  categoryRequired: "الفئة مطلوبة",
  selectCategory: "يرجى اختيار فئة الملاحظات",
  feedbackRequired: "الملاحظات مطلوبة",
  enterFeedback: "يرجى إدخال ملاحظاتك",
  thankYou: "شكراً لك!",
  feedbackSentDesc: "تم إرسال ملاحظاتك بنجاح. نحن نقدر مساهمتك!",
  ok: "موافق",
};
