const hairstyle = {
  title: "تسريحة الشعر",
  selectStyle: "اختر نوع التسريحة",
  selectColor: "اختر اللون",
  categories: {
    bangs: "غرة",
    short: "قصير",
    medium: "متوسط",
    long: "طويل",
    trendy: "عصري",
    natural: "طبيعي",
    vibrant: "حيوي",
    pastel: "باستيل",
    metallic: "معدني",
  },
  items: {
    // Style Names
    "curtain-bangs": "غرة ستارة",
    "full-bangs": "غرة كاملة",
    "side-bangs": "غرة جانبية",
    "wispy-bangs": "غرة ناعمة",
    "baby-bangs": "غرة قصيرة جداً",
    "pixie-cut": "قصة بيكسي",
    "bob-cut": "قصة بوب",
    "short-bob": "بوب قصير",
    "a-line-bob": "بوب متدرج",
    "inverted-bob": "بوب مقلوب",
    "shag-bob": "بوب فوضوي",
    "buzz-cut": "حلاقة صفر",
    undercut: "قصة أندركت",
    lob: "لوب (بوب طويل)",
    "shoulder-length": "طول الكتف",
    "layered-medium": "متوسط متدرج",
    "wolf-cut": "قصة الذئب",
    "shag-medium": "متوسط فوضوي",
    "wavy-medium": "مموج متوسط",
    "long-straight": "طويل ناعم",
    "long-wavy": "طويل مموج",
    "long-curly": "طويل كيرلي",
    "long-layers": "طويل متدرج",
    "mermaid-waves": "أمواج الحورية",
    "beach-waves": "أمواج الشاطئ",
    "butterfly-cut": "قصة الفراشة",
    "jellyfish-cut": "قصة قنديل البحر",
    "hush-cut": "قصة هادئة",
    "octopus-cut": "قصة الأخطبوط",
    mullet: "قصة موليت",
    shullet: "قصة شوليت",
    "mixie-cut": "قصة ميكسي",

    // Color Names
    "jet-black": "أسود فاحم",
    "natural-black": "أسود طبيعي",
    "dark-brown": "بني داكن",
    chocolate: "شوكولاتة",
    "medium-brown": "بني متوسط",
    "light-brown": "بني فاتح",
    chestnut: "كستنائي",
    auburn: "أوبورن",
    "red-brown": "بني محمر",
    strawberry: "أشقر فراولة",
    copper: "نحاسي",
    ginger: "زنجبيلي",
    "dark-blonde": "أشقر داكن",
    "golden-blonde": "أشقر ذهبي",
    "honey-blonde": "أشقر عسلي",
    "ash-blonde": "أشقر رمادي",
    platinum: "أشقر بلاتيني",
    white: "أبيض",
    gray: "رمادي",
    "salt-pepper": "ملح وفلفل",
    "fire-red": "أحمر ناري",
    "cherry-red": "أحمر كرزي",
    crimson: "قرمزي",
    burgundy: "برغندي",
    wine: "أحمر نبيذي",
    orange: "برتقالي زاهي",
    tangerine: "يوسفي",
    yellow: "أصفر زاهي",
    "neon-green": "أخضر نيون",
    emerald: "أخضر زمردي",
    turquoise: "فيروزي",
    "electric-blue": "أزرق كهربائي",
    "royal-blue": "أزرق ملكي",
    navy: "أزرق كحلي",
    purple: "أرجواني",
    violet: "بنفسجي",
    magenta: "ماجنتا",
    "hot-pink": "وردي صارخ",
    fuchsia: "فوشيا",
    "pastel-pink": "وردي باستيل",
    "baby-pink": "وردي فاتح",
    peach: "خوخي",
    "pastel-orange": "برتقالي باستيل",
    lemon: "أصفر ليموني",
    mint: "أخضر نعناعي",
    sage: "أخضر مريمية",
    seafoam: "رغوة البحر",
    "sky-blue": "أزرق سماوي",
    "baby-blue": "أزرق فاتح",
    periwinkle: "نبات الونكا",
    lavender: "لافندر",
    lilac: "ليلكي",
    mauve: "موف",
    "rose-gold": "ذهبي وردي",
    gold: "ذهبي",
    bronze: "برونزي",
    silver: "فضي",
    gunmetal: "رمادي معدني",
    "steel-blue": "أزرق فولاذي",
    rainbow: "قوس قزح",
    sunset: "ألوان الغروب",
    ocean: "ألوان المحيط",
    galaxy: "مجرة",
  },
  generate: "تغيير التسريحة",
  processing: "جاري المعالجة...",
  resultTitle: "نتيجة تسريحة الشعر",
  checkOut: "شاهد تسريحة شعري الجديدة!",
  generateError: "فشل توليد تسريحة الشعر. يرجى المحاولة مرة أخرى.",
  processingDesc: "جاري إنشاء {count} صور بـ {style} باللون {color}",
  permissionsError: "يرجى منح أذونات مكتبة الصور لتحميل الصور.",
};

export default hairstyle;
