const common = {
  appName: "SnackDream",
  loading: "Loading...",
  error: "Something went wrong",
  retry: "Retry",
  cancel: "Cancel",
  save: "Save",
  done: "Done",
  next: "Next",
  back: "Back",
  getStarted: "Get Started",
  continue: "Continue",
  skip: "Skip",
  confirm: "Confirm",
  delete: "Delete",
  imageResult: "Image Result",
  videoResult: "Video Result",
  saved: "Saved!",
  savedToGallery: "The image/video has been saved to your gallery.",
  deleteCreation: "Delete Creation",
  deleteConfirmMessage:
    "Are you sure you want to delete this creation? This action cannot be undone.",
  logout: "Log Out",
  logoutConfirm: "Do you really want to log out?",
  deleteAccount: "Delete Account",
  deleteAccountConfirm: "Permanently delete account? Everything will be lost.",
  privacyPolicy: "Privacy Policy",
  termsConditions: "Terms and Conditions",
  rateApp: "Rate App",
  feedback: "Feedback",
  contactUs: "Contact Us",
  home: "Home",
  profile: "Profile",
  credits: "Credits",
  images: "Images",
  creations: "Creations",
  community: "Community",
  share: "Share",
  copy: "Copy",
  copied: "Copied!",
  regenerate: "Regenerate",
  download: "Download",
  or: "or",
  removeImage: "Remove Image",
  removeImageConfirm: "Are you sure you want to remove this image?",
  remove: "Remove",
  optional: "Optional",
  maxImagesReached: "Maximum Reached",
  maxImagesDesc: "You can upload up to {max} images only",
  noImages: "No Images",
  noImagesDesc: "Please upload at least one image",
  noPrompt: "No Prompt",
  noPromptDesc: "Please enter a prompt",
  aiGenerate: "AI Generate",
  aiGenerateDesc: "Generating prompt with AI...",
  modelSelection: "Model Selection",
  modelSelectionDesc: "Select AI model",
  ok: "OK",
  oops: "Oops!",
  notExist: "This screen doesn't exist.",
  goHome: "Go to home screen!",
  unknownEffect: "Unknown Effect",
  unknownModel: "Unknown Model",
  all: "All",
  image: "Image",
  video: "Video",
};

export default common;
