export default {
  title: "Contact Us",
  desc: "Have a question or need help? We're here for you! Reach out through any of the methods below or send us a message.",
  getInTouch: "Get in Touch",
  sendMessage: "Send a Message",
  emailUs: "Email Us",
  name: "Name",
  email: "Email",
  subject: "Subject",
  message: "Message",
  namePlaceholder: "Your name",
  emailPlaceholder: "your@email.com",
  subjectPlaceholder: "What is this about?",
  messagePlaceholder: "Tell us how we can help...",
  send: "Send Message",
  requiredFields: "Required Fields",
  fillAllFields: "Please fill in all fields",
  invalidEmail: "Invalid Email",
  invalidEmailDesc: "Please enter a valid email address",
  messageSent: "Message Sent!",
  messageSentDesc:
    "Thank you for contacting us. We'll get back to you within 24-48 hours.",
  ok: "OK",
};
