const hairstyle = {
  title: "Hair Style",
  selectStyle: "Select Style",
  selectColor: "Select Color",
  categories: {
    bangs: "Bangs",
    short: "Short",
    medium: "Medium",
    long: "Long",
    trendy: "Trendy",
    natural: "Natural",
    vibrant: "Vibrant",
    pastel: "Pastel",
    metallic: "Metallic",
  },
  items: {
    // Style Names
    "curtain-bangs": "Curtain Bangs",
    "full-bangs": "Full Bangs",
    "side-bangs": "Side Swept Bangs",
    "wispy-bangs": "Wispy Bangs",
    "baby-bangs": "Baby Bangs",
    "pixie-cut": "Pixie Cut",
    "bob-cut": "Bob Cut",
    "short-bob": "Short Bob",
    "a-line-bob": "A-Line Bob",
    "inverted-bob": "Inverted Bob",
    "shag-bob": "Shag Bob",
    "buzz-cut": "Buzz Cut",
    undercut: "Undercut",
    lob: "Long Bob (Lob)",
    "shoulder-length": "Shoulder Length",
    "layered-medium": "Layered Medium",
    "wolf-cut": "Wolf Cut",
    "shag-medium": "Medium Shag",
    "wavy-medium": "Wavy Medium",
    "long-straight": "Long Straight",
    "long-wavy": "Long Wavy",
    "long-curly": "Long Curly",
    "long-layers": "Long Layers",
    "mermaid-waves": "Mermaid Waves",
    "beach-waves": "Beach Waves",
    "butterfly-cut": "Butterfly Cut",
    "jellyfish-cut": "Jellyfish Cut",
    "hush-cut": "Hush Cut",
    "octopus-cut": "Octopus Cut",
    mullet: "Modern Mullet",
    shullet: "Shullet",
    "mixie-cut": "Mixie Cut",

    // Color Names
    "jet-black": "Jet Black",
    "natural-black": "Natural Black",
    "dark-brown": "Dark Brown",
    chocolate: "Chocolate",
    "medium-brown": "Medium Brown",
    "light-brown": "Light Brown",
    chestnut: "Chestnut",
    auburn: "Auburn",
    "red-brown": "Red Brown",
    strawberry: "Strawberry",
    copper: "Copper",
    ginger: "Ginger",
    "dark-blonde": "Dark Blonde",
    "golden-blonde": "Golden Blonde",
    "honey-blonde": "Honey Blonde",
    "ash-blonde": "Ash Blonde",
    platinum: "Platinum Blonde",
    white: "White",
    gray: "Gray",
    "salt-pepper": "Salt & Pepper",
    "fire-red": "Fire Red",
    "cherry-red": "Cherry Red",
    crimson: "Crimson",
    burgundy: "Burgundy",
    wine: "Wine Red",
    orange: "Bright Orange",
    tangerine: "Tangerine",
    yellow: "Bright Yellow",
    "neon-green": "Neon Green",
    emerald: "Emerald Green",
    turquoise: "Turquoise",
    "electric-blue": "Electric Blue",
    "royal-blue": "Royal Blue",
    navy: "Navy Blue",
    purple: "Purple",
    violet: "Violet",
    magenta: "Magenta",
    "hot-pink": "Hot Pink",
    fuchsia: "Fuchsia",
    "pastel-pink": "Pastel Pink",
    "baby-pink": "Baby Pink",
    peach: "Peach",
    "pastel-orange": "Pastel Orange",
    lemon: "Lemon Yellow",
    mint: "Mint Green",
    sage: "Sage Green",
    seafoam: "Seafoam",
    "sky-blue": "Sky Blue",
    "baby-blue": "Baby Blue",
    periwinkle: "Periwinkle",
    lavender: "Lavender",
    lilac: "Lilac",
    mauve: "Mauve",
    "rose-gold": "Rose Gold",
    gold: "Gold",
    bronze: "Bronze",
    silver: "Silver",
    gunmetal: "Gunmetal",
    "steel-blue": "Steel Blue",
    rainbow: "Rainbow",
    sunset: "Sunset Ombre",
    ocean: "Ocean Ombre",
    galaxy: "Galaxy",
  },
  generate: "Generate Change",
  processing: "Processing...",
  resultTitle: "Hair Style Result",
  checkOut: "Check out my new hairstyle!",
  generateError: "Failed to generate hairstyle. Please try again.",
  processingDesc: "Creating {count} image(s) with {style} in {color}",
  permissionsError: "Please grant camera roll permissions to upload images.",
};

export default hairstyle;
